#!/bin/sh

# Cores
NC='\033[0m'
BBlue='\033[1;34m'
BRed='\033[1;31m'

REGEX_ISSUE_ID="[a-zA-Z0-9,.\_\-]+-[0-9]+"

BRANCH_NAME=$(git symbolic-ref --short HEAD)

ISSUE_ID=$(echo "$BRANCH_NAME" | grep -o -E "$REGEX_ISSUE_ID")

COMMIT_MESSAGE=$(cat "$1")

if [ -z "$ISSUE_ID" ]; then
    echo -e "${BRed}Branch não está no padrão que deveria mestre... ${NC}"
    exit 1
fi

echo_color() {
    printf "%b\n" "$1$2${NC}"
}

echo_color "$BBlue" "Verificando o nome da branch..."
if [ "$BRANCH_NAME" = "main" ] || [ "$BRANCH_NAME" = "develop" ]; then
    echo_color "$BRed" "Não é permitido commitar diretamente na branch '$BRANCH_NAME'."
    exit 1
fi

if [[ $COMMIT_MESSAGE == *$ISSUE_ID* ]]; then
    exit 0
fi
