#!/usr/bin/env sh

. "$(dirname -- "$0")/_/husky.sh"

./vendor/bin/phpstan
if [ $? -ne 0 ]; then
    echo "Opa... Deu ruim com o phpstan! Arrume antes de continuar 😅"
    exit 1
fi

php artisan test --parallel | php
if [ $? -ne 0 ]; then
    echo "Opa... Deu ruim com algum teste! Arrume antes de continuar 😅"
    exit 1
fi


STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep -E "\.php$") || true

for FILE in $STAGED_FILES; do
    ./vendor/bin/pint "$FILE" --test
    git add "$FILE"
done

exit 0
