#!/usr/bin/env sh

# Executa o PHPStan para verificação estática
./vendor/bin/phpstan --memory-limit=512M
if [ $? -ne 0 ]; then
    echo "Opa... Deu ruim com o phpstan! Arrume antes de continuar 😅"
    exit 1
fi


# Executa os testes paralelamente
php artisan test --parallel || exit_code=$?
if [ "$exit_code" -ne 0 ]; then
    echo "Opa... Deu ruim com algum teste! Arrume antes de continuar 🫣"
    exit 1
fi

# Formatação dos arquivos PHP com Pint
STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep -E "\.php$") || true
for FILE in $STAGED_FILES; do
    ./vendor/bin/pint "$FILE" --test
    git add "$FILE"
done

echo "Commit feito com sucesso! 😎🚀"
exit 0
